ДЗ hw_3
Yannh011/2024-07-otus-spring-Idiyatov pull request #3
Opened 2024-08-23 14:41 UTC by Yannh011

2024-08-26 23:36 UTC, VladimirMagerov requested changes

2024-08-26 23:36 UTC, VladimirMagerov commented on hw3/src/main/resources/application.yml
> +  locale: en-US
При смене локали переводятся только вопросы и ответы, но не сообщения самой программы. 
![image](https://github.com/user-attachments/assets/8f01460a-1f84-4c66-8bab-e08210d212a5)

2024-08-26 23:36 UTC, VladimirMagerov commented on hw3/src/test/java/ru/otus/hw/service/StudentServiceImplTest.java
> +    void determineCurrentStudent_ReturnsCorrectStudent() {
Тест падает

2024-08-28 18:54 UTC, Yannh011 commented on hw3/src/main/resources/application.yml
> +  locale: en-US
Поправил

2024-08-28 18:54 UTC, Yannh011 commented on hw3/src/test/java/ru/otus/hw/service/StudentServiceImplTest.java
> +    void determineCurrentStudent_ReturnsCorrectStudent() {
Поправил

2024-09-01 14:49 UTC, merged