ДЗ hw_8
Yannh011/2024-07-otus-spring-Idiyatov pull request #8
Opened 2024-10-17 15:52 UTC by Yannh011

2024-10-21 15:43 UTC, VladimirMagerov requested changes

2024-10-21 15:43 UTC, VladimirMagerov commented on hw8/src/main/java/ru/otus/hw/commands/BookCommands.java
> +    public String insertBook(String title, String authorId, String genreId) {
Создание новой книги создаёт книгу только с id=0 и постоянно её по этой id перезаписывает

2024-10-22 07:09 UTC, Yannh011 commented on hw8/src/main/java/ru/otus/hw/commands/BookCommands.java
> +    public String insertBook(String title, String authorId, String genreId) {
Поправил

2024-10-25 17:36 UTC, VladimirMagerov approved these changes

2024-10-26 15:01 UTC, merged